// <auto-generated />
namespace Ads.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class elmer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(elmer));
        
        string IMigrationMetadata.Id
        {
            get { return "201506061650573_elmer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
